name: youtube_bottom_navi_view_lego
description: "Youtube Bottom Navigation View"
#publish_to: 'none'
repository: https://github.com/flutter-lego/youtube_bottom_navi_view_lego

version: 1.0.4

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: #@add
  gap: #@add
  june_flow_util:
  styled_widget: #@add
  bot_toast:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
flutter:
  assets:
    - assets/lego/youtube_bottom_navi_view_lego/
  uses-material-design: true

topics:
  - lego